# Generated by Django 3.1.5 on 2021-01-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolution_chain',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
