# Generated by Django 3.1.5 on 2021-01-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0003_pokemon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon_stat',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
