# Generated by Django 3.1.5 on 2021-01-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0004_pokemon_stat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
